redoMinuts: 5
lang: en
minecraftTranslationsFile: null
checkUpdates: true
enablePrefix: true
saveCycle: 15
firstQuest: -1
maxLaunchedQuests: 0

debug: false

scoreboards: true

playerQuestUpdateMessage: true
playerStageStartMessage: true
allowPlayerCancelQuest: false
sounds: true
finishSound: ENTITY_PLAYER_LEVELUP
fireworks: true
mobsProgressBar: false
progressBarTimeoutSeconds: 15

gps: false
skillAPIoverride: true
accountsHook: false
splittedAdvancementPlaceholderMax: 3
disableTextHologram: false
hologramsHeight: 0.0
holoLaunchItemName: BOOK
holoTalkItemName: COAL
dynmap:
  markerSetName: "Quests"
  markerIcon: "bookshelf"

item: BOOK
pageItem: ARROW
questItem: "§e§oQuest Item"
itemNameColor: "§6"
itemAmountColor: "§e"
stageDescriptionItemsSplit:
  prefix: "§e- §6"
  showXOne: true
  sources: [SCOREBOARD, MENU]

start:
  enabled: true
  particleEffect: redstone
  particleColor:
    RED: 255
    BLUE: 0
    GREEN: 255
  particleShape: point
talk:
  enabled: true
  particleEffect: villager_happy
  particleColor:
    RED: 255
    BLUE: 0
    GREEN: 255
  particleShape: bar
next:
  enabled: true
  particleEffect: smoke_normal
  particleColor:
    RED: 255
    BLUE: 0
    GREEN: 255
  particleShape: spot